@startuml
actor User

rectangle "Authentication System" {
  usecase "Login via GitHub" as UC1
  usecase "Login via Facebook" as UC2
  usecase "Enter LMS" as UC3

}

User --> UC1
User --> UC2
UC1 --> UC3
UC2 --> UC3
@enduml
