server:
  port: 8086

spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://postgres:5432/library_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: reposting_service
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq-con
    port: 5672
    username: guest
    password: guest

  # Reporting-specific schema (shared DB strategy)
jpa.properties.hibernate.default_schema: reporting_service

# RabbitMQ custom configuration for event handling
reporting:
  queue: reporting.book-lent.queue
  exchange: lending.exchange
  routingKey: lending.book-lent
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
