server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: lending-service
  datasource:
    url: jdbc:postgresql://postgres:5432/library_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: lending_service

  rabbitmq:
    host: rabbitmq-con
    port: 5672
    username: guest
    password: guest

reader:
  service:
    url: http://reader-service:8085

book:
  service:
    url: http://book-service:8083


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

